# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0002_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='result_section_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='result_section_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
