# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-23 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biker", "0003_competition_add_section_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="section_2_domestic_only",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
