# Generated by Django 5.2 on 2025-04-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biker", "0006_multiple_competitions_20240615_0609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biker",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="biker.category",
            ),
            preserve_default=False,
        ),
    ]
