# Generated by Django 5.2 on 2025-04-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("domestic", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "verbose_name": "Biker",
                "verbose_name_plural": "Bikers",
                "ordering": ["surname", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ResultTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Result Template",
                "verbose_name_plural": "Result Templates",
            },
        ),
        migrations.CreateModel(
            name="CompetitionBiker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("domestic", models.BooleanField(blank=True, default=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "biker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_bikers",
                        to="competition.biker",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_bikers",
                        to="competition.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_bikers",
                        to="competition.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Biker",
                "verbose_name_plural": "Competition Bikers",
                "ordering": ["competition", "number"],
                "unique_together": {("competition", "number")},
            },
        ),
        migrations.CreateModel(
            name="CompetitionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_time", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "biker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="competition.competitionbiker",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="competition.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Change Log",
                "verbose_name_plural": "Competition Change Logs",
                "ordering": ["-change_time"],
            },
        ),
        migrations.CreateModel(
            name="ResultSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_number", models.IntegerField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[("caption", "Caption"), ("results", "Results")],
                        default="results",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("domestic_only", models.BooleanField(blank=True, default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="competition.category"
                    ),
                ),
                (
                    "result_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="competition.resulttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Section",
                "verbose_name_plural": "Result Sections",
                "ordering": ["section_number"],
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="result_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="competition.resulttemplate",
            ),
        ),
    ]
