# Generated by Django 5.2 on 2025-04-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionbiker",
            name="biker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="competition.biker",
            ),
        ),
    ]
