# Generated by Django 5.2 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0002_alter_competitionbiker_biker"),
    ]

    operations = [
        migrations.AddField(
            model_name="biker",
            name="comment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
