# Generated by Django 5.2 on 2025-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0003_biker_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
