# Generated by Django 5.2 on 2025-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0004_competition_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="biker",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
