# Generated by Django 5.2 on 2025-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0005_biker_birth_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="biker",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
